// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ixminnslfctprjnrgupe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4bWlubnNsZmN0cHJqbnJndXBlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NjYxNDEsImV4cCI6MjA3MzM0MjE0MX0.YxSbSkrfvFEg1LOGf0aGi0hE52s3jEcl7awSdndVpcQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});